### ISSUE TITLE
Predicate indicators involving parentheses should be recognised and turned into links

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pldoc#13]
For example, `library(clpfd)` contains the PlDoc comment:

    The constraints in/2, #=/2, #\=/2, #</2, #>/2, #=</2, and
    #>=/2 can be _reified_, which means reflecting their truth values...

The predicate references are detected and turned into links to their corresponding documentation entries. Strictly speaking though, these predicate indicators should actually be written using parentheses as in:

    ... (#=)/2, (#\=)/2, (#<)/2, (#>)/2, (#=<)/2 ...

because a term like `#=/2` is simply a syntax error , whereas `(#=)/2` is the intended predicate indicator.

However, when I change the PlDoc comments to contain the parentheses, these predicate references are no longer turned into links.

**Comment by JanWielemaker** [comment]
I'm not that sure.  There is nothing ambiguous: just take a non-blank sequence ending with /<int>.
It is what most people write.  It is also what is used in URLs because some browsers do not like
() or ''.  Note that if you wrote (#>)/2  and make that accepted, the system will probably emit it as
#>/2 anyway ...

**Comment by triska** [comment]
At least it would be great if the syntactically more correct version could be used in PlDoc. The link itself can still point to a reference that is acceptable for the web.

**Comment by JanWielemaker** [comment]
I see no reason.  Just complicates the recognition as we need (=)/2, ('=')/2, '='/2, = / 2, /(=,2), etc.
Works fine and simple as it is and if we really want we can render it all consistently as (=)/2.  I
think it confuses more than it solves though.
