### ISSUE TITLE
tcp_accept/3 does not appear in the generated documentation

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pldoc#14]
The predicate `tcp_accept/3` does not appear in the generated [documentation of `library(socket)`](http://eu.swi-prolog.org/pldoc/man?section=socket-predicates).

Maybe for this reason, none of the links to this predicate are resolved.

I hope you can install a check that automatically detects such situations in the future.

**Comment by JanWielemaker** [comment]
Added.
