### ISSUE TITLE
More flexible formatting of hyperlinks

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pldoc#15]
I have noticed two issues with **hyperlinks** in PlDoc:

1. Suppose I want to insert a link in the documentation, and let its description also show the link, so that the link is still there for example in the printed material. I tried to add a link like this:

        [http://eu.swi-prolog.org/man/clpfd.html](http://eu.swi-prolog.org/man/clpfd.html)

    and expect it to be formatted like this, i.e. a single hyperlink that displays the URL it links to:

    [http://eu.swi-prolog.org/man/clpfd.html](http://eu.swi-prolog.org/man/clpfd.html)

    Instead, I get in the generated documentation:

    &#91;[http://eu.swi-prolog.org/man/clpfd.html](http://eu.swi-prolog.org/man/clpfd.html)&#93;
([http://eu.swi-prolog.org/man/clpfd.html](http://eu.swi-prolog.org/man/clpfd.html))

    i.e., **two** successive links instead of only one.

2. Similarly, I would like to insert a **bold** link, naturally using:

        [**CLP(FD)**](http://eu.swi-prolog.org/man/clpfd.html)
    and expecting to see  [**CLP(FD)**](http://eu.swi-prolog.org/man/clpfd.html). Instead, I get

    &#91;**CLP(FD)**&#93;[(http://eu.swi-prolog.org/man/clpfd.html)](http://eu.swi-prolog.org/man/clpfd.html)

    that is, the text is formatted in bold, but the link is shown separately.

If possible, please enable these more flexible typesetting styles for hyperlinks. Thank you!

**Comment by JanWielemaker** [comment]
At (1), simply write the link, e.g., see http://www.example.com/ex  That is common wiki notation.
At (2), I pushed a better label recogniser.
