### ISSUE TITLE
Please clarify links to sections

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pldoc#17]
I am trying to link to a **section** within PlDoc.

The [documentation](http://www.swi-prolog.org/pldoc/doc_for?object=section%28%27packages/pldoc.html%27%29) about "Section Headers" reads:

> A section is named (labeled) using an optional sequence {	&#92;#name}.

I suspect the backslash is itself already a typo and this should rather read "... using an optional sequence **{#name}**".

In my example, I have a section with the header:

    ### Declarative integer arithmetic		{#clpfd-integer-arith}

and I managed to link to that section with:

    [**declarative integer arithmetic**](<#clpfd-integer-arith>)

Is this the official syntax and will it work also in the generated page? If so, please document this. Thank you in advance!

**Comment by triska** [comment]
Also one followup request:

When I link to a section (assuming this is the intended syntax) for example with:

> `See [declarative integer arithmetic](<#clpfd-integer-arith>).`

Then for the *online* version, it should of course turn into:

> See [declarative integer arithmetic](http://www.swi-prolog.org/pldoc/man?section=clpfd-integer-arith).

But for the **printed book** version, the link should turn into a reference like:

> See *declarative integer arithmetic* (Section A.8.3).

Therefore, please also document the difference between the online and printed version when linking to sections.

**Comment by triska** [comment]
Unfortunately, the links in the generated HTML files are broken. For example, *declarative integer arithmetic* in the [CLP(FD) documentation](http://eu.swi-prolog.org/man/clpfd.html) now links to:

    http://eu.swi-prolog.org/man/%5C#clpfd-integer-arith

and that does not work. It seems though as this could be salvaged by emitting the file name correctly when generating HTML.

Please clarify if this can be corrected, or if LaTeX must be used to link to different sections. In the latter case, I will move the whole CLP(FD) documentation to&nbsp;LaTeX.

**Comment by JanWielemaker** [comment]
`See [declarative integer arithmetic](<#clpfd-integer-arith>)`, etc now work.  Too many fixes for an easy update of the website though, so that will have to wait for the next release.  I'm planning a rather quick release this time.  Still, I think LaTeX would do a better job for writing such extensive documentation.

**Comment by triska** [comment]
Thank you Jan, could you please document this syntax for linking to sections in PlDoc? And in particular, is there a way in PlDoc to create a link such that it comes out as *Section X.Y.Z* in the generated&nbsp;HTML? This seems to be the default for section references in the LaTeX toolchain.

**Comment by JanWielemaker** [comment]
At the moment, `<#id>` is translated into `\secref{id}` by the LaTeX backend and (thus)

    [label](<#id>)

becomes

    label (section X.Y.Z)

I consider this mostly a hack.   Not something I'd like to promote right now at least.

**Comment by triska** [comment]
I think although the HTML generation may now work, using `--pldoc` directly is now broken for such links. For example, when I do:

    $ swipl --pldoc clpfd.pl

thin it shows me the predicate index. When I click on the entry of `(#<==>)/2`, it takes me to:

    http://localhost:50906/doc_for?object=clpfd%3A%20%28%23%3C%3D%3D%3E%29/2

This works as intended. On this entry, the first sentences are:

    P and Q are equivalent. See reification. 

The link for **reification** leads me to:

    http://localhost:50906/doc_for?object=clpfd%3A%20%28%23%3C%3D%3D%3E%29/2#clpfd-reification

and that **does not** show me the intended section. This previously worked!
