### ISSUE TITLE
Code formatting does not work when the code starts with a dot

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-pldoc#19]
Code formatting does not work when the code start with a dot.

Example: `=.gz=` at http://www.swi-prolog.org/pldoc/doc_for?object=http_reply_file/3

**Comment by JanWielemaker** [comment]
Use =|.gz|= for arbitrary sequences.

**Comment by triska** [comment]
Wouter, just to add a bit more info: This is explained in the section "[Empahizing [sic] text](http://www.swi-prolog.org/pldoc/doc_for?object=section%28%27packages/pldoc.html%27%29)", which could in my view use a major overhaul:

> Note that <tt>=&lt;identifier&gt;=</tt> is limited to a [sic] an *identifier*, such as a file name, XML name, etc. Identifiers **must start and end with an alphanumerical character**, while characters from the set&nbsp;`.-/:` may appear internally. 

Note also the table entry:

> `=|code|=` Typeset text fixed font. Content can be long. 

where what is "long" is nowhere defined.

**Comment by wouterbeek** [comment]
Would it be correct if I substitute [1a,2a] with [1b,2b] for all three occurrences?

[1a]   "Typeset text STYLE font for identifiers (see running text)."
[1b]   "Typeset identifiers (see running text for definition) using STYLE font."
[2a]   "Typeset text STYLE font.  Content can be long."
[2b]   "Typeset arbitrary text using STYLE font.
