### ISSUE TITLE
Feature request: Hyperlinks to external resources in PDF

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pldoc#20]
Currently, **hyperlinks** that are included in the LaTeX sources of the manual (using&nbsp;`\url[Text]{URL}`) are shown correctly in the HTML output, but *not* in&nbsp;PDF, even though the PDF format does allow links to external resources.

I see that there is code in `main.doc` to enable `hyperref` when the printed **BOOK** is produced. Please consider enabling this LaTeX package also for the regular PDF&nbsp;manual.

**Comment by triska** [comment]
I have made some progress with this, by translating links to `\href{URL}{Description}` for the LaTeX version. 

Please see the following commit:

https://github.com/triska/packages-pldoc/commit/b3138c80571519da6c895f65ad26910211c8241d

However, as explained in the commit message, this currently does not work for links that contain for example&nbsp;`~`. Please advice on the best way to retain the verbatim destinations in such cases.

**Comment by JanWielemaker** [comment]
`\url[label]{URL}` is use throughout.  It doesn't appear to actually create a link any more.   The `man` dir contains `url.sty`, which wasn't generally available in LaTeX back then and at some point worked with hyperref.    It is also use to define the \Sxxx commands that deal with special character sequences.  What needs to happen is

  - Figure out what is wrong with the bundled `url.sty`.  Can it be replaced by a standard package? In
     that case, what must change?
  - Change this throughout the LaTeX files (if needed)
  - Adjust doc_latex.pl to emit the right thing.

**Comment by JanWielemaker** [comment]
The short story seems to be

  - Drop our copy of url.tex (it is in texlive)
  - Use \url{...} and \href{URL}{Text} (latter replacing \url[Text]{URL})
  - `~`  is allowed in the above inside the URL, so we should not rewrite it to `\Stilde{}`

I'll see how much work that is.

**Comment by JanWielemaker** [comment]
Seems fixed now.  Thanks.
