### ISSUE TITLE
SWI-Prolog extensions are incorrectly rendered in HTML

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pldoc#21]
Please see the [title](http://eu.swi-prolog.org/pldoc/man?section=ext-list-motivation):

> 5.1.1 Motivating ' ' and[]for lists

There are 2 issues:

1. the `[|]` is *not rendered at all*
2. there is no whitespace around `[]`.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed.

**Comment by triska** [comment]
Only the first of the two issues is fixed, as far as I can see.
