### ISSUE TITLE
undocumented privates don't appear (low priority)

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/packages-pldoc#22]
1. Make a module with two public and one private predicate
2. Add a valid pldoc comment to one of the public predicates
3. consult, start doc_server and browse page for the module.
4. Click the 'export only/private' button at top of web page
5. observe that page reloads
EXPECTED: warning about undocumented public predicate and undocumented private predicate
OBSERVED: only the public is warned about

If you document the private, it works correctly.

I could see the argument that this is expected behavior

**Comment by JanWielemaker** [comment]
I can't really consider that a bug.  I think a demand to document all private code is for Prolog at least two bridges too far.  Just think of all the helper rules to get argument order right, introduce an accumulator
variable, etc.  You really don't want these documented.

**Comment by Anniepoo** [comment]
OKey dokey, I can buy that. Closing
