### ISSUE TITLE
@arg tag includes too many lines

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/packages-pldoc#23]
Example 

```

%! add_triple(+Base:atom, +Context:context, +Instance:instance) is det
%
%	@arg Base the base to add to
%	@arg Context the context/3 term defining the event
%	@arg Instance the instance being recorded
%
% Add a single triple to the base
% 
add_triple(Base, Context, Instance) :-
      Instance is Base + Context.  % random body so its valid
```

Serve this through pldoc.  Last line should be normal size font, instead it's 80% font, because it's included in the TD tag of the preceeding @arg

**Comment by Anniepoo** [comment]
PS, no , it's not a windows line ending issue

**Comment by Anniepoo** [comment]
Note that swapping the order of args and description and replacing tabs with a single space solves it, but is uncomfortably restrictive

**Comment by JanWielemaker** [comment]
As with JavaDoc from which PlDoc is derived, @keyword sequences must be at the end of the description block and each @keyword takes input until the next or end of the comment block.  I think that is ok.  More freedom is nice, but also requires more complicated rules to explain.

**Comment by Anniepoo** [comment]
Probably something to cover in a tutorial.
