### ISSUE TITLE
Parser does not recognize italic text in some cases

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pldoc#26]
As a case that illustrates this issue, please consider [**`cryptolib.md`**](https://github.com/SWI-Prolog/packages-ssl/blob/master/cryptolib.md)

One of the last paragraphs consists of the following Markdown:

<pre>
Bob  receives <b>`j*G`</b>  in plain  text and  can arrive  at the  same shared
secret  by  performing   the  calculation <b>`k*(j*G)`</b>,  which   is  -  by
associativity and commutativity of  scalar multiplication - identical to
the point <b>`j*(k*G)`</b>,  which is again Q from which  the shared secret can
be derived, and the message can be decrypted with evp_decrypt/6.
</pre>

In the above, I would actually like to use *italic* text everywhere I am currently using `backquoted` text (which I highlighted in the snipped above). So, I replace all 6&nbsp;occurrences of a backquote with an underscore:

<pre>
Bob  receives <b>_j*G_</b>  in plain  text and  can arrive  at the  same shared
secret  by  performing   the  calculation  <b>_k*(j*G)_</b>,  which   is  -  by
associativity and commutativity of  scalar multiplication - identical to
the point <b>_j*(k*G)_</b>,  which is again Q from which  the shared secret can
be derived, and the message can be decrypted with evp_decrypt/6.
</pre>

I then use `make doc` to generate `ssl.html`.

**Expectation**: *italic* text, i.e., expressions like <i>j* G</i>, <i>k*(j*G)</i> etc.

**Result**: The *underscores* themselves occur in the text, i.e., _ j * G _, _ k * ( j * G) _ etc.

It works exactly as expected if I only apply the above change to the *first* expression (j*G), but not if I apply it to all three of them.

If possible, please make italic text usable for all 3 expressions in this paragraph, because that is what I am using also in other places of this file.

**Comment by JanWielemaker** [comment]
Font switches do not allow other symbols in between to avoid ambiguity.  `...` demands valid Prolog syntax.  Use _|...|_, etc. to specify fonts for content that contains symbol characters.

**Comment by triska** [comment]
I do *not* consider this issue fixed: The very same syntax, `_j*G_`, works in all other instances in this file and yields italic text, but not in this paragraph. I have tried `/j*G/`, and it does not yield italic&nbsp;text.

**Comment by JanWielemaker** [comment]
`/.../` doesn't mean anything.  It turns out it doesn't want to process this paragraph at all though.  That is wrong.

**Comment by JanWielemaker** [comment]
Made a few changes.   Fixes these issues.  The whole thing dealing with in-paragraph sequences requires some more thinking about what takes priority over what though.

**Comment by triska** [comment]
I have now pushed a patch that uses italics as originally intended in this paragraph, and it works exactly as expected when I use the most recent PlDoc version to generate the HTML&nbsp;file. Thank you!

One additional complication of these issues is that discussing them via Markdown is extremely error-prone in itself. See for example your statements:  "Use _|...|_, etc. to specify fonts for content that contains symbol characters." followed by "/.../ doesn't mean anything".

This arises because `_|...|_` is rendered to look like `/.../` on GitHub.

**Comment by JanWielemaker** [comment]
That holds (to some extend) for all markup languages :)
