### ISSUE TITLE
Bold links are rendered incorrectly

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pldoc#27]
[clpfdlib.md](https://github.com/SWI-Prolog/swipl-devel/blob/master/man/lib/clpfdlib.md) contains the following text, using Markdown&nbsp;syntax to generate a&nbsp;link:

<pre>
Read [**The Power of Prolog**](https://www.metalevel.at/prolog) to understand how this
library is meant to be used in practice.
</pre>

**Expectation**: I expect this to be rendered as:

<blockquote>
Read <a href="https://www.metalevel.at/prolog"><b>The Power of Prolog</b></a> to understand how this library is meant to be used in practice.
</blockquote>

This works as expected up to and including SWI-Prolog 7.5.9.

**Current result**: With the current git version, I now obtain for the same text the *unintended* rendering:

<blockquote>
Read <a href="https://www.metalevel.at/prolog">**The Power of Prolog**</a> to understand how this library is meant to be used in practice.
</blockquote>

If possible, please re-enable the original rendering so that we can embed bold links.

**Comment by JanWielemaker** [comment]
Seems to work again with 363c966b9ee8903c31139a7c1be0f52b871f27cb
