### ISSUE TITLE
Additional issue with italic text

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pldoc#29]
The [CLP(FD) documentation](http://eu.swi-prolog.org/pldoc/man?section=clpfd) contains the following (source) text:

<pre>
the general [CLP(_X_)
scheme](<#clp>)
</pre>

**Expectation**:

I expect this to be rendered as:

<blockquote>
the general CLP(<i>X</i>) scheme (<a href="http://eu.swi-prolog.org/pldoc/man?section=clp">section 7</a>)
</blockquote>

**Result**:

However, it is currently rendered as:

<blockquote>
the general CLP(_X_) scheme (<a href="http://eu.swi-prolog.org/pldoc/man?section=clp">section 7</a>)
</blockquote>

This seems to be related to but slightly different from #28.

**Comment by triska** [comment]
I think the parenthesis is the culprit, because I also see this now in `library(crypto)`, in cases where I write for example:

<pre>
use crypto_password_hash/3 (with a specified _salt_)
</pre>

**Expectation**:

<blockquote>
use <tt>crypto_password_hash/3</tt> (with a specified <i>salt</i>)
</blockquote>

**Result**:

<blockquote>
use <tt>crypto_password_hash/3</tt> (with a specified _salt_)
</blockquote>

**Comment by JanWielemaker** [comment]
Fixed.  I also did some more work on the test definition environment.  Enjoy using in the `pldoc` package using

    swipl test_wiki.pl

and open `http://localhost:4040/`.  This could serve as a tool to create lots of tests.  As is, I mostly consider using it for debugging such issues and adding a test case for them.  Still need to write code to run the tests without a browser.
